from events import views
from django.urls import path
urlpatterns = [
    path('', views.home, name='home'),
    path('events/', views.list_events, name='list-events'),
    path('free-events/', views.list_free_events, name='list-free-events'),
    path('events/<str:title>/', views.event_detail, name='event-detail'),
    path('upcoming-events/', views.list_upcoming_events,
         name='list-upcoming-events'),
    path('paid-events/', views.list_paid_events, name='list-paid-events'),
    path('event-participant-count/', views.event_participant_count,
         name='event-participant-count'),
    path('participant-event-count/', views.participant_event_count,
         name='participant-event-count'),
    path('event-payments/', views.events_payment_processing, name='event-payments'),
    path('event-payments/<int:event_id>/',
         views.event_payment_processing, name='event-payment-detail'),
    path('payment/<int:payment_id>/',
         views.event_payment_detail, name='payment-detail'),
    path('speakers/', views.list_speakers, name='list-speakers'),
    path('speakers/<str:email>/', views.speaker_detail, name='speaker-detail'),
    path('participants/', views.list_participants, name='list-participants'),
    path('participants/<str:email>/',
         views.participant_detail, name='participant-detail'),
    path('event/<int:event_id>/total-payment/',
         views.event_total_payment, name='event-total-payment'),
    path('average-paid-event-price/', views.average_paid_event_price,
         name='average-paid-event-price'),
    path('event/<int:event_id>/participants/',
         views.event_participants, name='event-participants'),
    path('event/<int:event_id>/speakers/',
         views.event_speakers, name='event-speakers'),
    path('schedule/<str:topic>/', views.schedule_detail, name='schedule-detail'),
    path('schedules/', views.list_of_schedule, name='list-of-schedule'),
]
